aio_georss_client>=0.12
python-dateutil>=2.9.0
